[package]
name = "my-first"
version = "0.1.0"
authors = ["castelg8 <castelg8@RTCMW030142>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
